/**
 * Copyright (c) Forward Email LLC
 * SPDX-License-Identifier: BUSL-1.1
 */

const crypto = require('node:crypto');
const { Buffer } = require('node:buffer');

const basicAuth = require('basic-auth');

const env = require('#config/env');
const { isSetupComplete } = require('#helpers/is-setup-complete');

function safeEqual(a, b) {
  const bufferA = Buffer.from(String(a));
  const bufferB = Buffer.from(String(b));
  return (
    bufferA.length === bufferB.length &&
    crypto.timingSafeEqual(bufferA, bufferB)
  );
}

//
// Self-hosted first-run protection: while no admin account exists yet, the
// entire site is behind the HTTP Basic Auth credentials generated by
// setup.sh so only the operator can register the first (admin) account.
// Once the admin exists the gate disappears automatically — no .env edit
// or restart required. Set AUTH_BASIC_ALWAYS=true to keep enforcing it.
//
function setupGate(auth) {
  return async function (ctx, next) {
    const config = require('#config');

    if (!config.isSelfHosted || !auth || !auth.name || !auth.pass)
      return next();

    if (!env.AUTH_BASIC_ALWAYS && (await isSetupComplete())) return next();

    const credentials = basicAuth(ctx.req);
    if (
      credentials &&
      safeEqual(credentials.name, auth.name) &&
      safeEqual(credentials.pass, auth.pass)
    )
      return next();

    ctx.set('WWW-Authenticate', 'Basic realm="Forward Email Setup"');
    ctx.status = 401;
    ctx.body = 'Unauthorized';
  };
}

//
// While no admin exists, funnel browser traffic to the /setup wizard
//
async function setupRedirect(ctx, next) {
  const config = require('#config');

  if (!config.isSelfHosted) return next();
  if (ctx.method !== 'GET' || !ctx.accepts('html')) return next();

  const path = ctx.pathWithoutLocale || ctx.path;

  // never redirect the wizard itself, auth flows, or static assets
  if (
    path === '/setup' ||
    path.startsWith('/setup/') ||
    path === config.loginRoute ||
    path === '/register' ||
    path === '/logout' ||
    path.startsWith('/auth/') ||
    path.startsWith('/.well-known') ||
    path.startsWith('/css') ||
    path.startsWith('/js') ||
    path.startsWith('/img') ||
    path.startsWith('/fonts') ||
    path.startsWith('/browserconfig') ||
    path.startsWith('/robots') ||
    path.startsWith('/site.webmanifest') ||
    path.startsWith('/favicon')
  )
    return next();

  if (await isSetupComplete()) return next();

  ctx.redirect(ctx.state.l ? ctx.state.l('/setup') : '/setup');
}

module.exports = { setupGate, setupRedirect };
