services:

  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
    - redis-data:/data
    env_file:
      - .env

volumes:
  mongodb-data:
  redis-data:
